root@kali:~/RainFall# python
Python 2.7.14+ (default, Mar 13 2018, 15:23:44)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pwn
>>> p32(0x0804fff5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'p32' is not defined
>>> from pwn import *
>>> p32(0x0804fff5)
'\xf5\xff\x04\x08'
>>> p32(0x0804fff5)
'\xf5\xff\x04\x08'
>>> u32(\xf5\xff\x04\x08)
  File "<stdin>", line 1
    u32(\xf5\xff\x04\x08)
                        ^
SyntaxError: unexpected character after line continuation character
>>> u32("\xf5\xff\x04\x08")
134545397
>>> u32("\xf5\xff\x04\x08")





























































